import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen flex flex-col', inter.className)}>
        <header className='flex justify-between px-24 py-8'>
          <img src='/logo.svg' alt='logo' />
          <div>
            <Button className='bg-transparent text-[#0077B6]'>Login</Button>
            <Button className='bg-[#0077B6] rounded-full'>Sign Up</Button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
