name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - "pages/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./src
      
      - name: Create .env.local
        run: |
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env.local
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.local
        working-directory: ./src

      - name: Display .env.local
        run: cat .env.local
        working-directory: ./src

      - name: Linting
        run: npm run lint
        working-directory: ./src

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXT_PUBLIC_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        working-directory: ./src

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./src
