name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - "pages/*" # This triggers the workflow on any branch that starts with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd src && npm install

      - name: Linting
        run: cd src && npm run lint

      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          directory: src
          file_name: .env.local

      - name: Build
        run: cd src && npm run build

      - name: Deploy to Vercel
        run: vercel --prod src/
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
